apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-app-svc
spec:
  type: NodePort
  selector:
    app: ping-pong-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001