apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      securityContext:
        runAsUser: 0 # set to use root permissions to be able to write files
      volumes:
      - name: random-image
        persistentVolumeClaim:
          claimName: random-image-pvclaim
      priorityClassName: high-priority-nonpreempting
      containers:
      - name: todo-app
        image: TODO-PROJECT/FRONTEND-IMAGE
        volumeMounts:
        - name: random-image
          mountPath: /usr/src/app/files
        env:
        - name: PORT
          value: "3000"
        - name: RANDOM_IMAGE_MOUNTPATH
          value: "/usr/src/app/files"
        - name: RANDOM_IMAGE_FILENAME
          value: "random_image.jpg"
        - name: PICSUM_URL
          value: "https://picsum.photos/1200"
        - name: TODO_BACKEND_URL
          value: "http://todo-backend-svc/todos"


