apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-todo-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-backup-cronjob
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: 
            - /bin/sh
            - -c
            - pg_dump -U $POSTGRES_USER -h $POSTGRES_HOST $POSTGRES_DATABASE > todo-database-backup.sql
            - gcloud storage cp ./todo-database-backup.sql gs://todo-database-backup-bucket
            envFrom:
            - configMapRef:
                name: todo-backend-configmap
          restartPolicy: OnFailure