apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-backup-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-backup-cronjob
            image: juhanikat/backup-database:c
            imagePullPolicy: IfNotPresent
            command: 
            - /bin/sh
            - -c
            args: 
              - |
                apt-get update
                apt-get install -y curl
                apt-get install -y python
                curl https://sdk.cloud.google.com > install.sh
                chmod 777 ./install.sh
                ./install.sh --disable-prompts
                gcloud auth activate-service-account --key-file=./service-account-key.json
                gcloud config set project dwk-gke-468909
                apt-get install -y postgresql-client
                export PGPASSWORD='$POSTGRES_PASSWORD'
                pg_dump -U $POSTGRES_USER -h $POSTGRES_HOST $POSTGRES_DATABASE > todo-database-backup.sql
                gcloud storage cp ./todo-database-backup.sql gs://todo-database-backup-bucket
            envFrom:
            - configMapRef:
                name: todo-backend-configmap
          restartPolicy: OnFailure